#apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
#kind: Deployment
#metadata:
#  name: training-data-crawler-deployment
#spec:
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        app: training-data-crawler
#    spec:
#      containers:
#      - name: training-data-crawler
#        image:55dennisdenuto/property-price-collector:latest
#
apiVersion: batch/v1
kind: Job
metadata:
  name: property-crawler-jobs
spec:
  template:
    metadata:
      name: property-crawler
    spec:
      containers:
        - name: training-data-crawler-1
          image: dennisdenuto/property-price-collector:latest
          env:
          - name: START_POSTCODE
            value: "2000"
          - name: END_POSTCODE
            value: "2155"
      restartPolicy: OnFailure
